RecipeFormatVersion: '2020-01-25'
ComponentName: COMPONENT_NAME
ComponentVersion: COMPONENT_VERSION
ComponentDescription: Home Assistant
ComponentPublisher: Amazon
ComponentConfiguration:
  DefaultConfiguration:
    secretArn: $SECRET_ARN
    accessControl:
      aws.greengrass.SecretManager:
        aws.greengrass.labs.HomeAssistant:secrets:1:
          policyDescription: Allows access to the Home Assistant configuration secret
          operations:
          - "aws.greengrass#GetSecretValue"
          resources:
          - $SECRET_ARN
ComponentDependencies:
  aws.greengrass.DockerApplicationManager:
    VersionRequirement: '>=2.0.0'
  aws.greengrass.SecretManager:
    VersionRequirement: '>=2.0.0'
    DependencyType: HARD
Manifests:
- Platform:
    os: linux
  Lifecycle:
    Install:
      RequiresPrivilege: true
      Script: |-
        echo Creating virtual environment
        python3 -m venv venv
        echo Activating virtual environment
        . venv/bin/activate
        echo Upgrading pip
        pip install pip --upgrade
        echo Installing package requirements
        pip3 install awsiotsdk
        echo Installing the component artifacts
        cp -R {artifacts:decompressedPath}/home-assistant/* .
        python3 -u install.py {configuration:/secretArn}
    Startup:
      RequiresPrivilege: true
      Script: |-
        echo Activating virtual environment
        . venv/bin/activate
        echo Running the component
        docker-compose up -d
    Shutdown:
      RequiresPrivilege: true
      Script: docker-compose down
    Recover:
      RequiresPrivilege: true
      Script: docker-compose down
  Artifacts:
  - Uri: docker:$DOCKER_IMAGE
  - Uri: s3://BUCKET_NAME/COMPONENT_VERSION/home-assistant.zip
    Unarchive: ZIP
    Permission:
      Read: ALL
Lifecycle: {}
