# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

version: 0.2

phases:
  pre_build:
    commands:
      # Install pre-requisite tools
      - pip3 install -r requirements.txt
      - pip3 install git+https://github.com/aws-greengrass/aws-greengrass-gdk-cli.git

      # Log the versions of all tools
      - python3 --version
      - pylint --version
      - pytest --version
      - gdk --version
  
  build:
    commands:
      # Perform static analysis on our Python source before we use it for anything else
      - pylint artifacts libs tests *.py

      # Run our unit tests 
      - pytest --junit-xml=junit.xml --cov=artifacts --cov=.

      # Create the pre-release component version we'll use for this CI build. Use build number as patch revision.
      - VERSION=$(jq -r '.component."aws.greengrass.labs.HomeAssistant".version' gdk-config.json)
      - CI_VERSION=$(echo $VERSION | cut -d . -f 1,2).$CODEBUILD_BUILD_NUMBER
      - echo CI build version is $CI_VERSION

      # Write back to gdk-config.json so that GDK gets the CI build version
      - jq --arg CI_VERSION "$CI_VERSION" '.component."aws.greengrass.labs.HomeAssistant".version = $CI_VERSION' gdk-config.json > tmp.json && mv tmp.json gdk-config.json
      - cat gdk-config.json

      # Build and publish the component
      - gdk component build
      - gdk component publish

  post_build:
    commands:

artifacts:
  discard-paths: yes
  files:
    - greengrass-build/**/*
    - gdk-config.json
    - junit.xml

reports:
  UnitTestsReport:
    files:
      - junit.xml
