# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

version: 0.2

phases:
  pre_build:
    commands:
      # Install pre-requisite tools
      - pip3 install -r requirements.txt
      - pip3 install git+https://github.com/aws-greengrass/aws-greengrass-gdk-cli.git

      # Log the versions of all tools
      - python3 --version
      - pylint --version
      - pytest --version
      - gdk --version
  
  build:
    commands:
      # Perform static analysis on our Python source before we use it for anything else
      - pylint artifacts libs tests *.py

      # Run our unit tests 
      - pytest --junit-xml=junit.xml --cov=artifacts --cov=.

      # Build and publish the component
      - gdk component build
      - gdk component publish

  post_build:
    commands:

artifacts:
  discard-paths: yes
  files:
    - greengrass-build/**/*
    - junit.xml

reports:
  UnitTestsReport:
    files:
      - junit.xml
